// <auto-generated />
namespace HMS.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AccomodationType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AccomodationType));
        
        string IMigrationMetadata.Id
        {
            get { return "202105261654052_AccomodationType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
